# Generated by Django 4.0.2 on 2022-03-22 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password_slug_field',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password_char_field',
            field=models.CharField(blank=True, db_column='password_char_field_db_column', db_index=True, db_tablespace='password_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">password_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(128)], verbose_name='Пароль от аккаунта пользователя'),
        ),
    ]
