# Generated by Django 4.0.2 on 2022-03-07 05:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_field', models.CharField(blank=True, db_column='qualification_field_db_column', db_index=True, db_tablespace='qualification_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">qualification_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='qualification_field')),
                ('image_field', models.ImageField(blank=True, db_column='image_field_db_column', db_index=True, db_tablespace='image_field_db_tablespace', default='uploads/vacancy/default_vacancy.jpg', error_messages=False, help_text='<small class="text-muted">>image_field</small><hr><br>', max_length=200, null=True, upload_to='uploads/vacancy/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='image_field')),
                ('datetime_field', models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">datetime_field</small><hr><br>', null=True, verbose_name='datetime_field')),
                ('sphere_field', models.CharField(blank=True, db_column='sphere_field_db_column', db_index=True, db_tablespace='sphere_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">sphere_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='sphere_field')),
                ('education_field', models.CharField(blank=True, db_column='education_field_db_column', db_index=True, db_tablespace='education_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">education_field</small><hr><br>', max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='education_field')),
                ('rank_field', models.CharField(blank=True, db_column='rank_field_db_column', db_index=True, db_tablespace='rank_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">rank_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='rank_field')),
                ('experience_field', models.CharField(blank=True, db_column='experience_field_db_column', db_index=True, db_tablespace='experience_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">experience_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='experience_field')),
                ('schedule_field', models.CharField(blank=True, db_column='schedule_field_db_column', db_index=True, db_tablespace='schedule_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">schedule_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='schedule_field')),
                ('description_field', models.TextField(blank=True, db_column='description_field_db_column', db_index=True, db_tablespace='description_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">description_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='description_field')),
                ('author_field', models.ForeignKey(blank=True, db_column='author_field_db_column', db_tablespace='author_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.usermodel', verbose_name='author_field')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy_model_table',
                'ordering': ('-datetime_field',),
            },
        ),
    ]
