# Generated by Django 4.0.2 on 2022-03-29 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='type_char_field',
            field=models.CharField(blank=True, choices=[('logging_action', 'Логирование действий'), ('print_action', 'Вывод в консоль действий'), ('logging_error', 'Логирование ошибок'), ('print_error', 'Вывод в консоль ошибок'), ('logging_response', 'Логирование ответов'), ('print_response', 'Вывод в консоль ответов'), ('scheduler_personal', 'Планировщик обновления персонала из 1С'), ('scheduler_superuser', 'Планировщик создания стандартных суперпользователей'), ('scheduler_group', 'Планировщик создания стандартных групп')], db_column='type_char_field_db_column', db_index=True, db_tablespace='type_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">char_field[0, 300]</small><hr><br>', max_length=300, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(300)], verbose_name='Тип'),
        ),
    ]
