# Generated by Django 4.0.2 on 2022-03-12 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_ideamodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideamodel',
            options={'ordering': ('-created_datetime_field',), 'verbose_name': 'Идея в банке идей', 'verbose_name_plural': 'Идеи в банке идей'},
        ),
        migrations.RemoveField(
            model_name='ideamodel',
            name='comment_postmoderate_char_field',
        ),
        migrations.RemoveField(
            model_name='ideamodel',
            name='postmoderate_foreign_key_field',
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='comment_moderate_char_field',
            field=models.CharField(blank=True, db_column='comment_moderate_char_field_db_column', db_index=True, db_tablespace='comment_moderate_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">comment_moderate_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='comment_moderate_char_field'),
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='moderate_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='moderate_foreign_key_field_db_column', db_tablespace='moderate_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">moderate_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderate_foreign_key_field', to='backend.usermodel', verbose_name='moderate_foreign_key_field'),
        ),
    ]
