# Generated by Django 4.0.2 on 2022-03-07 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_vacancymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='description_field',
            field=models.TextField(blank=True, db_column='description_field_db_column', db_index=True, db_tablespace='description_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">description_field</small><hr><br>', max_length=512, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(512)], verbose_name='description_field'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='education_field',
            field=models.CharField(blank=True, db_column='education_field_db_column', db_index=True, db_tablespace='education_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">education_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='education_field'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='experience_field',
            field=models.CharField(blank=True, db_column='experience_field_db_column', db_index=True, db_tablespace='experience_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">experience_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='experience_field'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='qualification_field',
            field=models.CharField(blank=True, db_column='qualification_field_db_column', db_index=True, db_tablespace='qualification_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">qualification_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='qualification_field'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='rank_field',
            field=models.CharField(blank=True, db_column='rank_field_db_column', db_index=True, db_tablespace='rank_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">rank_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='rank_field'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='schedule_field',
            field=models.CharField(blank=True, db_column='schedule_field_db_column', db_index=True, db_tablespace='schedule_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">schedule_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='schedule_field'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='sphere_field',
            field=models.CharField(blank=True, db_column='sphere_field_db_column', db_index=True, db_tablespace='sphere_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">sphere_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='sphere_field'),
        ),
    ]
