# Generated by Django 4.0.2 on 2022-03-10 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_groupmodel_name_char_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationalmodel',
            name='status_moderate_char_field',
            field=models.CharField(blank=True, db_column='status_moderate_char_field_db_column', db_index=True, db_tablespace='status_moderate_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">status_moderate_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='status_moderate_char_field'),
        ),
    ]
