# Generated by Django 4.0.2 on 2022-03-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_settingsmodel_type_char_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationalmodel',
            name='sphere_char_field',
        ),
    ]
