# Generated by Django 4.0.2 on 2022-03-25 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_settingsmodel_type_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='type_slug_field',
            field=models.SlugField(blank=True, choices=[('logging', 'Логирование'), ('error', 'Ошибки'), ('scheduler', 'Планировщик'), ('default_superusers', 'Суперпользователи')], db_column='type_slug_field_db_column', db_tablespace='type_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">type_slug_field</small><hr><br>', max_length=500, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(500)], verbose_name='type_slug_field'),
        ),
    ]
