# Generated by Django 4.0.2 on 2022-03-08 15:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_vacancymodel_description_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_field', models.CharField(blank=True, db_column='qualification_field_db_column', db_index=True, db_tablespace='qualification_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">qualification_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='qualification_field')),
                ('last_name_field', models.CharField(blank=True, db_column='last_name_field_db_column', db_index=True, db_tablespace='last_name_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">last_name_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='last_name_field')),
                ('first_name_field', models.CharField(blank=True, db_column='first_name_field_db_column', db_index=True, db_tablespace='first_name_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">first_name_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='first_name_field')),
                ('patronymic_field', models.CharField(blank=True, db_column='patronymic_field_db_column', db_index=True, db_tablespace='patronymic_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">patronymic_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='patronymic_field')),
                ('image_field', models.ImageField(blank=True, db_column='image_field_db_column', db_index=True, db_tablespace='image_field_db_tablespace', default='uploads/vacancy/default_vacancy.jpg', error_messages=False, help_text='<small class="text-muted">>image_field</small><hr><br>', max_length=200, null=True, upload_to='uploads/vacancy/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='image_field')),
                ('datetime_birth_field', models.DateTimeField(blank=True, db_column='datetime_birth_field_db_column', db_index=True, db_tablespace='datetime_birth_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">datetime_birth_field</small><hr><br>', null=True, verbose_name='datetime_birth_field')),
                ('datetime_create_field', models.DateTimeField(blank=True, db_column='datetime_create_field_db_column', db_index=True, db_tablespace='datetime_create_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">datetime_create_field</small><hr><br>', null=True, verbose_name='datetime_create_field')),
                ('education_field', models.CharField(blank=True, db_column='education_field_db_column', db_index=True, db_tablespace='education_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">education_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='education_field')),
                ('experience_field', models.CharField(blank=True, db_column='experience_field_db_column', db_index=True, db_tablespace='experience_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">experience_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='experience_field')),
                ('sex_field', models.CharField(blank=True, db_column='sex_field_db_column', db_index=True, db_tablespace='sex_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">sex_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='sex_field')),
                ('contact_data_field', models.TextField(blank=True, db_column='contact_data_field_db_column', db_index=True, db_tablespace='contact_data_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">contact_data_field</small><hr><br>', max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(250)], verbose_name='contact_data_field')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'db_table': 'resume_model_table',
                'ordering': ('-datetime_create_field',),
            },
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='rank_field',
            field=models.CharField(blank=True, db_column='rank_field_db_column', db_index=True, db_tablespace='rank_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">rank_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='rank_field'),
        ),
    ]
