# Generated by Django 4.0.2 on 2022-03-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rationalmodel_status_moderate_char_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationalmodel',
            name='conclusion_postmoderate_char_field',
        ),
        migrations.RemoveField(
            model_name='rationalmodel',
            name='conclusion_premoderate_char_field',
        ),
    ]
