# Generated by Django 4.0.2 on 2022-03-25 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_settingsmodel_type_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='datetime_field',
            field=models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">datetime_field</small><hr><br>', null=True, verbose_name='datetime_field'),
        ),
    ]
