# Generated by Django 4.0.2 on 2022-03-12 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_ideamodel_register_datetime_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideamodel',
            name='category_char_field',
            field=models.CharField(blank=True, db_column='category_char_field_db_column', db_index=True, db_tablespace='category_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">category_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='comment_moderate_char_field',
            field=models.CharField(blank=True, db_column='comment_moderate_char_field_db_column', db_index=True, db_tablespace='comment_moderate_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">comment_moderate_char_field</small><hr><br>', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(200)], verbose_name='comment_moderate_char_field'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='description_text_field',
            field=models.TextField(blank=True, db_column='description_text_field_db_column', db_index=True, db_tablespace='description_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">description_text_field</small><hr><br>', max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(3000)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='name_char_field',
            field=models.CharField(blank=True, db_column='name_char_field_db_column', db_index=True, db_tablespace='name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">name_char_field</small><hr><br>', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(200)], verbose_name='Название рац. предложения'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='place_char_field',
            field=models.CharField(blank=True, db_column='place_char_field_db_column', db_index=True, db_tablespace='place_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">place_char_field</small><hr><br>', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)], verbose_name='Предполагаемое место внедрения'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='sphere_char_field',
            field=models.CharField(blank=True, db_column='sphere_char_field_db_column', db_index=True, db_tablespace='sphere_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">sphere_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Сфера рационализаторского предложения'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='status_moderate_char_field',
            field=models.CharField(blank=True, db_column='status_moderate_char_field_db_column', db_index=True, db_tablespace='status_moderate_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">status_moderate_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='status_moderate_char_field'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='subdivision_char_field',
            field=models.CharField(blank=True, db_column='subdivision_char_field_db_column', db_index=True, db_tablespace='subdivision_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">subdivision_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Наименование структурного подразделения'),
        ),
    ]
