# Generated by Django 4.0.2 on 2022-03-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_rationalmodel_conclusion_postmoderate_char_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationalmodel',
            name='author_postmoderate_char_field',
        ),
        migrations.RemoveField(
            model_name='rationalmodel',
            name='author_premoderate_char_field',
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='postmoderate_foreign_key_field_2',
            field=models.ForeignKey(blank=True, db_column='postmoderate_foreign_key_field_2_db_column', db_tablespace='postmoderate_foreign_key_field_2_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">postmoderate_foreign_key_field_2</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmoderate_foreign_key_field_2', to='backend.usermodel', verbose_name='postmoderate_foreign_key_field_2'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='premoderate_foreign_key_field_1',
            field=models.ForeignKey(blank=True, db_column='premoderate_foreign_key_field_1_db_column', db_tablespace='premoderate_foreign_key_field_1_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">premoderate_foreign_key_field_1</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premoderate_foreign_key_field_1', to='backend.usermodel', verbose_name='premoderate_foreign_key_field_1'),
        ),
    ]
