# Generated by Django 4.0.2 on 2022-03-12 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_ideamodel_category_char_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideamodel',
            name='moderate_foreign_key_field',
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='idea_moderate_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='idea_moderate_foreign_key_field_db_column', db_tablespace='idea_moderate_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">idea_moderate_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_moderate_foreign_key_field', to='backend.usermodel', verbose_name='idea_moderate_foreign_key_field'),
        ),
        migrations.CreateModel(
            name='IdeaRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_boolean_field', models.BooleanField(blank=True, db_column='status_boolean_field_db_column', db_index=True, db_tablespace='status_boolean_field_db_tablespace', default=True, error_messages=False, help_text='<small class="text-muted">status_boolean_field</small><hr><br>', verbose_name='Лайк / дизлайк')),
                ('datetime_field', models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">Дата и время, example: "31.12.2021Т23:59:59"</small><hr><br>', null=True, verbose_name='Дата создания')),
                ('author_foreign_key_field', models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.usermodel', verbose_name='Автор')),
                ('idea_foreign_key_field', models.ForeignKey(blank=True, db_column='idea_foreign_key_field_db_column', db_tablespace='idea_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">idea_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ideamodel', verbose_name='Идея')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': '1_Идеи_Рейтинги',
                'db_table': 'idea_rating_model_table',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IdeaCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField(blank=True, db_column='text_field_db_column', db_index=True, db_tablespace='text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">text_field</small><hr><br>', max_length=512, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(512)], verbose_name='Комментарий')),
                ('datetime_field', models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">Дата и время, example: "31.12.2021Т23:59:59"</small><hr><br>', null=True, verbose_name='Дата создания')),
                ('author_foreign_key_field', models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.usermodel', verbose_name='Автор')),
                ('idea_foreign_key_field', models.ForeignKey(blank=True, db_column='idea_foreign_key_field_db_column', db_tablespace='idea_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">idea_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ideamodel', verbose_name='Идея')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': '1_Идеи_Комментарии',
                'db_table': 'idea_comment_model_table',
                'ordering': ('-id',),
            },
        ),
    ]
