# Generated by Django 4.0.2 on 2022-03-10 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0005_remove_rationalmodel_author_postmoderate_char_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplesmodel',
            name='foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='foreign_key_field_db_column', db_tablespace='foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Связь, с каким-либо объектом, example: "to=User.objects.get(username="Bogdan")"</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_field', to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='foreign_key_field'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='group_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='group_foreign_key_field_db_column', db_tablespace='group_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Связь, с какой-либо группой, example: "to=Group.objects.get(name="User")"</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_foreign_key_field', to='auth.group', verbose_name='Группа:'),
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='author_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_foreign_key_field', to='backend.usermodel', verbose_name='Автор рац. предложения'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='user_foreign_key_field_db_column', db_tablespace='user_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Связь, с каким-либо пользователем, example: "to=User.objects.get(username="Bogdan")"</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_foreign_key_field', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='author_field',
            field=models.ForeignKey(blank=True, db_column='author_field_db_column', db_tablespace='author_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_field', to='backend.usermodel', verbose_name='author_field'),
        ),
    ]
