# Generated by Django 4.0.2 on 2022-03-25 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_settingsmodel_type_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='type_slug_field',
            field=models.SlugField(blank=True, choices=[('actions_logging', 'Логирование действий'), ('actions_print', 'Вывод действий в консоль'), ('error_logging', 'Логирование ошибок'), ('error_print', 'Вывод в консоль действий'), ('scheduler_personal_1c', 'Планировщик обновления персонала из 1С'), ('scheduler_default_superusers', 'Планировщик создания стандартных суперпользователей'), ('scheduler_default_groups', 'Планировщик создания стандартных групп')], db_column='type_slug_field_db_column', db_tablespace='type_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">type_slug_field</small><hr><br>', max_length=500, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(500)], verbose_name='type_slug_field'),
        ),
    ]
