# Generated by Django 4.0.2 on 2022-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_ideacommentmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdeaCommentModel',
            new_name='CommentIdeaModel',
        ),
        migrations.RenameModel(
            old_name='IdeaRatingModel',
            new_name='RatingIdeaModel',
        ),
    ]
