# Generated by Django 4.0.2 on 2022-03-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_settingsmodel_type_slug_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodel',
            options={'ordering': ('name_slug_field',), 'verbose_name': 'Группа расширенная', 'verbose_name_plural': 'Admin 2, Группы расширение'},
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='group_foreign_key_field',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='name_char_field',
        ),
    ]
