# Generated by Django 4.0.2 on 2022-03-25 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_groupmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionmodel',
            options={'ordering': ('access_slug_field',), 'verbose_name': 'Действие', 'verbose_name_plural': 'Admin 3, Действия'},
        ),
        migrations.AlterModelOptions(
            name='loggingmodel',
            options={'ordering': ('-datetime_field',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Admin 5, Логи'},
        ),
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'ordering': ('-created_datetime_field',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Admin 6, Уведомления'},
        ),
        migrations.RemoveField(
            model_name='actionmodel',
            name='name_char_field',
        ),
        migrations.AlterField(
            model_name='actionmodel',
            name='access_slug_field',
            field=models.SlugField(blank=True, db_column='access_slug_field_db_column', db_tablespace='access_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted underline">access_slug_field</small><hr><br>', max_length=500, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(500)], verbose_name='access_slug_field'),
        ),
    ]
