# Generated by Django 4.0.2 on 2022-03-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_ideacommentmodel_commentideamodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentideamodel',
            options={'ordering': ('-id',), 'verbose_name': 'Комментарий идеи', 'verbose_name_plural': 'Банк идей, комментарии'},
        ),
        migrations.AlterModelOptions(
            name='ideamodel',
            options={'ordering': ('-created_datetime_field',), 'verbose_name': 'Идея', 'verbose_name_plural': 'Банк идей, идеи'},
        ),
        migrations.AlterModelOptions(
            name='ratingideamodel',
            options={'ordering': ('-id',), 'verbose_name': 'Рейтинг идеи', 'verbose_name_plural': 'Банк идей, рейтинги'},
        ),
    ]
