# Generated by Django 4.0.2 on 2022-03-25 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_actionmodel_options_alter_loggingmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='integer_field',
            field=models.IntegerField(blank=True, db_column='integer_field_db_column', db_index=True, db_tablespace='integer_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">integer_field</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='integer_field'),
        ),
    ]
