# Generated by Django 4.0.2 on 2022-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_commentideamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingideamodel',
            name='datetime_field',
            field=models.DateTimeField(auto_now_add=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', error_messages=False, help_text='<small class="text-muted">datetime_field</small><hr><br>', null=True, verbose_name='Дата и время создания'),
        ),
    ]
