# Generated by Django 3.2.9 on 2021-12-06 09:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerVisionModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_char_field', models.CharField(blank=True, db_column='name_char_field_db_column', db_index=True, db_tablespace='name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">короткое и лаконичное имя для модуля</small><hr><br>', max_length=32, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Имя модуля:')),
                ('description_text_field', models.TextField(blank=True, db_column='description_text_field_db_column', db_index=True, db_tablespace='description_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">описание для модуля</small><hr><br>', max_length=512, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(512)], verbose_name='Описание модуля:')),
                ('path_slug_field', models.SlugField(blank=True, choices=[('16_operation', 'Грохота, 16 операция, 26 отметка'), ('26_operation', 'Грохота, 26 операция, ?? отметка')], db_column='path_slug_field_db_column', db_tablespace='path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">полный путь от класса до функции вызова цикла модуля</small><hr><br>', max_length=32, null=True, unique=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Путь модуля:')),
                ('play_boolean_field', models.BooleanField(blank=True, db_column='play_boolean_field_db_column', db_index=True, db_tablespace='play_boolean_field_db_tablespace', default=False, error_messages=False, help_text='<small class="text-muted">нужно ли запускать модуль каждый тик главного цикла событий</small><hr><br>', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Запуск работы модуля:')),
                ('delay_float_field', models.FloatField(blank=True, db_column='delay_float_field_db_column', db_index=True, db_tablespace='delay_float_field_db_tablespace', default=0.0, error_messages=False, help_text='<small class="text-muted">время для тика каждого компонента в модуле</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)], verbose_name='Задержка цикла модуля:')),
                ('datetime_field', models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">дата и время последнего тика модуля</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='datetime_field')),
                ('duration_field', models.DurationField(blank=True, db_column='duration_field_db_column', db_index=True, db_tablespace='duration_field_db_tablespace', default=datetime.timedelta(0), error_messages=False, help_text='<small class="text-muted">длительность последнего тика модуля</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='duration_field')),
                ('restart_boolean_field', models.BooleanField(blank=True, db_column='restart_boolean_field_db_column', db_index=True, db_tablespace='restart_boolean_field_db_tablespace', default=False, error_messages=False, help_text='<small class="text-muted">нужно ли перезапускать модуль после ошибки</small><hr><br>', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рестарт модуля после ошибки:')),
                ('error_text_field', models.TextField(blank=True, db_column='error_text_field_db_column', db_index=True, db_tablespace='error_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">описание исключения и/или ошибки модуля</small><hr><br>', max_length=512, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(512)], verbose_name='Текст исключения-ошибки модуля:')),
            ],
            options={
                'verbose_name': 'Computer Vision Module',
                'verbose_name_plural': 'Computer Vision Modules',
                'db_table': 'computer_vision_module_model_table',
                'ordering': ('name_char_field', 'path_slug_field'),
            },
        ),
    ]
