# Generated by Django 3.2.9 on 2021-12-06 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_computervisionmodulemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='description_text_field',
            field=models.TextField(blank=True, db_column='description_text_field_db_column', db_index=True, db_tablespace='description_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">описание для модуля</small><hr><br>', max_length=1024, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1024)], verbose_name='Описание модуля:'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='error_text_field',
            field=models.TextField(blank=True, db_column='error_text_field_db_column', db_index=True, db_tablespace='error_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">описание исключения и/или ошибки модуля</small><hr><br>', max_length=2048, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(2048)], verbose_name='Текст исключения-ошибки модуля:'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='name_char_field',
            field=models.CharField(blank=True, db_column='name_char_field_db_column', db_index=True, db_tablespace='name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">короткое и лаконичное имя для модуля</small><hr><br>', max_length=64, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='Имя модуля:'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='path_slug_field',
            field=models.SlugField(blank=True, choices=[('16_operation', 'Грохота, 16 операция, 26 отметка'), ('26_operation', 'Грохота, 26 операция, ?? отметка')], db_column='path_slug_field_db_column', db_tablespace='path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">полный путь от класса до функции вызова цикла модуля</small><hr><br>', max_length=128, null=True, unique=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Путь модуля:'),
        ),
    ]
