# Generated by Django 3.2.9 on 2021-11-27 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_alter_usermodel_options'),
        ('app_admin', '0003_ideacommentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_boolean_field', models.BooleanField(blank=True, db_column='status_boolean_field_db_column', db_index=True, db_tablespace='status_boolean_field_db_tablespace', default=True, error_messages=False, help_text='<small class="text-muted">status_boolean_field</small><hr><br>', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Лайк / дизлайк')),
                ('datetime_field', models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">Дата и время, example: "31.12.2021Т23:59:59"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Дата создания')),
                ('author_foreign_key_field', models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.usermodel', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор')),
                ('idea_foreign_key_field', models.ForeignKey(blank=True, db_column='idea_foreign_key_field_db_column', db_tablespace='idea_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">idea_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.ideamodel', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Идея')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': '1_Идеи_Рейтинги',
                'db_table': 'idea_rating_model_table',
                'ordering': ('-id',),
            },
        ),
    ]
