# Generated by Django 3.2.9 on 2021-12-06 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_auto_20211206_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computervisionmodulemodel',
            name='duration_field',
        ),
        migrations.AddField(
            model_name='computervisionmodulemodel',
            name='duration_float_field',
            field=models.FloatField(blank=True, db_column='duration_float_field_db_column', db_index=True, db_tablespace='duration_float_field_db_tablespace', default=0.0, error_messages=False, help_text='<small class="text-muted">длительность последнего тика модуля</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)], verbose_name='Длительность операции:'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='datetime_field',
            field=models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">дата и время последнего тика модуля</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='datetime_field'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='delay_float_field',
            field=models.FloatField(blank=True, db_column='delay_float_field_db_column', db_index=True, db_tablespace='delay_float_field_db_tablespace', default=3.0, error_messages=False, help_text='<small class="text-muted">время для тика каждого компонента в модуле</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)], verbose_name='Задержка цикла модуля:'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='restart_boolean_field',
            field=models.BooleanField(blank=True, db_column='restart_boolean_field_db_column', db_index=True, db_tablespace='restart_boolean_field_db_tablespace', default=True, error_messages=False, help_text='<small class="text-muted">нужно ли перезапускать модуль после ошибки</small><hr><br>', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рестарт модуля после ошибки:'),
        ),
    ]
