# Generated by Django 3.2.9 on 2021-11-27 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_idearatingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideamodel',
            name='category_char_field',
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='category_slug_field',
            field=models.SlugField(blank=True, db_column='category_slug_field_db_column', db_tablespace='category_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">category_char_field</small><hr><br>', max_length=16, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(16)], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='short_description_char_field',
            field=models.CharField(blank=True, db_column='short_description_char_field_db_column', db_index=True, db_tablespace='short_description_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">short_description_char_field</small><hr><br>', max_length=64, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='Краткое описание'),
        ),
    ]
