# Generated by Django 3.2.9 on 2021-12-06 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_auto_20211206_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerVisionComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genericipaddress_field', models.GenericIPAddressField(blank=True, db_column='genericipaddress_field_db_column', db_index=True, db_tablespace='genericipaddress_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">ip-адрес<hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Ip адрес:')),
            ],
            options={
                'verbose_name': 'Computer Vision Component',
                'verbose_name_plural': 'Computer Vision Components',
                'db_table': 'computer_vision_component_model_table',
                'ordering': ('genericipaddress_field',),
            },
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='path_slug_field',
            field=models.SlugField(blank=True, choices=[('16_operation', 'Грохота, 16 операция, 10 отметка'), ('26_operation', 'Грохота, 26 операция, 10 отметка')], db_column='path_slug_field_db_column', db_tablespace='path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">полный путь от класса до функции вызова цикла модуля</small><hr><br>', max_length=128, null=True, unique=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Путь модуля:'),
        ),
    ]
