# Generated by Django 3.2.9 on 2021-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_auto_20211206_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computervisioncomponentmodel',
            options={'ordering': ('genericipaddress_field', 'play_boolean_field'), 'verbose_name': 'Computer Vision Component', 'verbose_name_plural': 'Computer Vision Components'},
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='play_boolean_field',
            field=models.BooleanField(blank=True, db_column='play_boolean_field_db_column', db_index=True, db_tablespace='play_boolean_field_db_tablespace', default=False, error_messages=False, help_text='<small class="text-muted">нужно ли запускать компонент каждый тик</small><hr><br>', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Запуск работы компонента:'),
        ),
    ]
