# Generated by Django 3.2.9 on 2021-12-08 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_auto_20211206_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='alias_char_field',
            field=models.CharField(blank=True, db_column='alias_char_field_db_column', db_index=True, db_tablespace='alias_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">псевдоним, используемый для отображения или записи в стороннюю базу</small><hr><br>', max_length=64, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='Псевдоним компонента:'),
        ),
        migrations.AlterField(
            model_name='computervisionmodulemodel',
            name='path_slug_field',
            field=models.SlugField(blank=True, choices=[('16_operation', 'Грохота, 16 операция, 10 отметка'), ('26_operation', 'Грохота, 26 операция, 10 отметка'), ('36_operation', 'Грохота, 36 операция, 10 отметка')], db_column='path_slug_field_db_column', db_tablespace='path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">полный путь от класса до функции вызова цикла модуля</small><hr><br>', max_length=128, null=True, unique=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Путь модуля:'),
        ),
    ]
