# Generated by Django 3.2.9 on 2021-12-08 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_auto_20211208_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='mask_char_field',
            field=models.CharField(blank=True, db_column='mask_char_field_db_column', db_index=True, db_tablespace='mask_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">путь от главной папки к папке с изображением-маской: "static/media/data/computer_vision/temp"</small><hr><br>', max_length=64, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='Путь к маске компонента:'),
        ),
    ]
