# Generated by Django 3.2.9 on 2021-12-08 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_computervisioncomponentmodel_mask_char_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computervisioncomponentmodel',
            options={'ordering': ('play_boolean_field', 'alias_char_field', 'genericipaddress_field'), 'verbose_name': 'Computer Vision Component', 'verbose_name_plural': 'Computer Vision Components'},
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='alarm_level_integer_field',
            field=models.IntegerField(blank=True, db_column='alarm_level_field_db_column', db_index=True, db_tablespace='alarm_level_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">alarm_level</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='alarm_level'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='bright_level_integer_field',
            field=models.IntegerField(blank=True, db_column='bright_level_integer_field_db_column', db_index=True, db_tablespace='bright_level_integer_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">bright_level</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='bright_level'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='correct_coefficient_float_field',
            field=models.FloatField(blank=True, db_column='correct_coefficient_float_field_db_column', db_index=True, db_tablespace='correct_coefficient_float_field_db_tablespace', default=0.0, error_messages=False, help_text='<small class="text-muted">correct_coefficient_</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='correct_coefficient_'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='count_not_zero_integer_field',
            field=models.IntegerField(blank=True, db_column='count_not_zero_integer_field_db_column', db_index=True, db_tablespace='count_not_zero_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">count_not_zero</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='count_not_zero'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='in_range_set_from_integer_field',
            field=models.IntegerField(blank=True, db_column='in_range_set_from_integer_field_db_column', db_index=True, db_tablespace='bright_level_integer_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">in_range_set_from</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='in_range_set_from'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='in_range_set_to_integer_field',
            field=models.IntegerField(blank=True, db_column='in_range_set_to_integer_field_db_column', db_index=True, db_tablespace='in_range_set_to_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">in_range_set_to</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='in_range_set_to'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='login_slug_field',
            field=models.SlugField(blank=True, db_column='login_protocol_slug_field_db_column', db_tablespace='login_protocol_slug_field_db_tablespace', default='admin', error_messages=False, help_text='<small class="text-muted">логин от источника компонента: "admin"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(50)], verbose_name='Логин источника компонента:'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='module_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='module_foreign_key_field_db_column', db_tablespace='module_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">связь, к какому модулю относится компонент</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.computervisionmodulemodel', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Модуль компонента:'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='null_level_integer_field',
            field=models.IntegerField(blank=True, db_column='null_level_field_db_column', db_index=True, db_tablespace='null_level_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">null_level</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='null_level'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='password_slug_field',
            field=models.SlugField(blank=True, db_column='password_protocol_slug_field_db_column', db_tablespace='password_protocol_slug_field_db_tablespace', default='q1234567', error_messages=False, help_text='<small class="text-muted">пароль от источника компонента: "q1234567"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(50)], verbose_name='Пароль источника компонента:'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='point_1_1_integer_field',
            field=models.IntegerField(blank=True, db_column='point_1_1_field_db_column', db_index=True, db_tablespace='point_1_1_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">point_1_1</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='point_1_1'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='point_1_2_integer_field',
            field=models.IntegerField(blank=True, db_column='point_1_2_field_db_column', db_index=True, db_tablespace='point_1_2_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">point_1_2</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='point_1_2'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='point_1_3_integer_field',
            field=models.IntegerField(blank=True, db_column='point_1_3_field_db_column', db_index=True, db_tablespace='point_1_3_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">point_1_3</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='point_1_3'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='point_2_1_integer_field',
            field=models.IntegerField(blank=True, db_column='point_2_1_field_db_column', db_index=True, db_tablespace='point_2_1_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">point_2_1</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='point_2_1'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='point_2_2_integer_field',
            field=models.IntegerField(blank=True, db_column='point_2_2_field_db_column', db_index=True, db_tablespace='point_2_2_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">point_2_2</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='point_2_2'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='point_2_3_integer_field',
            field=models.IntegerField(blank=True, db_column='point_2_3_field_db_column', db_index=True, db_tablespace='point_2_3_field_db_tablespace', default=0, error_messages=False, help_text='<small class="text-muted">point_2_3</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='point_2_3'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='port_integer_field',
            field=models.IntegerField(blank=True, db_column='port_integer_field_db_column', db_index=True, db_tablespace='port_integer_field_db_tablespace', default=80, error_messages=False, help_text='<small class="text-muted">порт соединения: "80" / "434"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Порт api источника компонента:'),
        ),
        migrations.AddField(
            model_name='computervisioncomponentmodel',
            name='protocol_slug_field',
            field=models.SlugField(blank=True, db_column='protocol_slug_field_db_column', db_tablespace='protocol_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">способ соединения с api: "http://" / "rtsp://" / "https://"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(50)], verbose_name='Протокол api источника компонента:'),
        ),
        migrations.AlterField(
            model_name='computervisioncomponentmodel',
            name='genericipaddress_field',
            field=models.GenericIPAddressField(blank=True, db_column='genericipaddress_field_db_column', db_index=True, db_tablespace='genericipaddress_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">ip адрес в формате: "192.168.15.202"<hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Ip адрес источника компонента:'),
        ),
        migrations.AlterField(
            model_name='computervisioncomponentmodel',
            name='play_boolean_field',
            field=models.BooleanField(blank=True, db_column='play_boolean_field_db_column', db_index=True, db_tablespace='play_boolean_field_db_tablespace', default=False, error_messages=False, help_text='<small class="text-muted">нужно ли делать расчёты каждый тик в этом компоненте</small><hr><br>', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Запуск работы компонента:'),
        ),
    ]
