# Generated by Django 3.2.9 on 2021-12-08 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_auto_20211208_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computervisioncomponentmodel',
            name='bright_level_integer_field',
            field=models.IntegerField(blank=True, db_column='bright_level_integer_field_db_column', db_index=True, db_tablespace='bright_level_integer_field_db_tablespace', default=100, error_messages=False, help_text='<small class="text-muted">bright_level</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='bright_level'),
        ),
        migrations.AlterField(
            model_name='computervisioncomponentmodel',
            name='protocol_slug_field',
            field=models.SlugField(blank=True, db_column='protocol_slug_field_db_column', db_tablespace='protocol_slug_field_db_tablespace', default='http://', error_messages=False, help_text='<small class="text-muted">способ соединения с api: "http://" / "rtsp://" / "https://"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(50)], verbose_name='Протокол api источника компонента:'),
        ),
    ]
