# Generated by Django 4.0 on 2022-01-10 19:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_slug_field', models.SlugField(blank=True, db_column='username_slug_field_db_column', db_tablespace='username_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Тут отображается идентификатор пользователя, например: </small><hr><br>', max_length=12, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(12)], verbose_name='Имя пользователя')),
                ('ip_genericipaddress_field', models.GenericIPAddressField(blank=True, db_column='ip_genericipaddress_field_field_db_column', db_index=True, db_tablespace='ip_genericipaddress_field_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Строка содержащая ip-адрес, example: "127.0.0.1"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(12)], verbose_name='Ip адрес клиента')),
                ('request_path_slug_field', models.SlugField(blank=True, db_column='request_path_slug_field_field_db_column', db_tablespace='request_path_slug_field_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Строка содержащая путь обращения, example: "https://.../home/"</small><hr><br>', max_length=128, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Действие пользователя')),
                ('request_method_slug_field', models.SlugField(blank=True, db_column='request_method_slug_field_field_db_column', db_tablespace='request_method_slug_field_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">GET: просмотр страницы, POST: отправка данных из формы</small><hr><br>', max_length=4, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(4)], verbose_name='Метод запроса')),
                ('error_text_field', models.TextField(blank=True, db_column='error_text_field_db_column', db_index=True, db_tablespace='error_text_field_db_tablespace', default='error: ', error_messages=False, help_text='<small class="text-muted">Много текста, example: "текст, текст..."</small><hr><br>', max_length=512, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(512)], verbose_name='Текст ошибки и/или исключения')),
                ('datetime_field', models.DateTimeField(blank=True, db_column='datetime_field_db_column', db_index=True, db_tablespace='datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">Дата и время, example: "31.12.2021Т23:59:59"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Дата и время записи')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'db_table': 'logging_admin_model_table',
                'ordering': ('-datetime_field',),
            },
        ),
    ]
