# Generated by Django 4.0 on 2021-12-21 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_ideasmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasmodel',
            name='author_char_field',
            field=models.CharField(blank=True, db_column='author_char_field_db_column', db_index=True, db_tablespace='author_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">author_char_field</small><hr><br>', max_length=32, null=True, unique=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Автор'),
        ),
    ]
