# Generated by Django 4.0 on 2022-01-10 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_loggingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleOrComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_slug_field', models.SlugField(blank=True, choices=[('0_module', 'Модуль'), ('1_section', 'Секция'), ('2_component', 'Компонент')], db_column='type_slug_field_db_column', db_tablespace='type_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Строка текста валидная для ссылок и системных вызовов, example: "success"</small><hr><br>', max_length=64, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='Тип:')),
                ('name_char_field', models.CharField(blank=True, db_column='name_char_field_db_column', db_index=True, db_tablespace='name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Небольшая срока текста, example: "текст, текст"</small><hr><br>', max_length=128, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Название:')),
                ('previous_path_slug_field', models.SlugField(blank=True, db_column='previous_path_slug_field_db_column', db_tablespace='previous_path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Строка текста валидная для ссылок и системных вызовов, example: "success"</small><hr><br>', max_length=128, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Ссылка назад:')),
                ('current_path_slug_field', models.SlugField(blank=True, db_column='current_path_slug_field_db_column', db_tablespace='current_path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Строка текста валидная для ссылок и системных вызовов, example: "success"</small><hr><br>', max_length=128, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Ссылка текущая:')),
                ('next_path_slug_field', models.SlugField(blank=True, db_column='next_path_slug_field_db_column', db_tablespace='next_path_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Строка текста валидная для ссылок и системных вызовов, example: "success"</small><hr><br>', max_length=128, null=True, unique=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Ссылка вперёд:')),
                ('position_float_field', models.FloatField(blank=True, db_column='position_float_field_db_column', db_index=True, db_tablespace='position_float_field_db_tablespace', default=1.0, error_messages=False, help_text='<small class="text-muted">Число с плавающей запятой, example: "0.0"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Позиция в модулях:')),
                ('image_field', models.ImageField(blank=True, db_column='image_field_db_column', db_index=True, db_tablespace='image_field_db_tablespace', default='admin/module/module.png', error_messages=False, help_text='<small class="text-muted">>Файл, с расширением изображения, example: "example.jpg(/png/bpm...)"</small><hr><br>', null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, upload_to='uploads/admin/module', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='file_field')),
                ('text_field', models.TextField(blank=True, db_column='text_field_db_column', db_index=True, db_tablespace='text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">Много текста, example: "текст, текст..."</small><hr><br>', max_length=256, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='Описание:')),
            ],
            options={
                'verbose_name': 'Модуль или компонент',
                'verbose_name_plural': 'Модули и компоненты',
                'db_table': 'module_or_component_admin_model_table',
                'ordering': ('type_slug_field', 'current_path_slug_field', 'position_float_field', 'name_char_field'),
            },
        ),
    ]
