# Generated by Django 4.0 on 2021-12-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_datamodel_todomodel_ideasmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModel',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='author_foreign_key_field',
        ),
        migrations.DeleteModel(
            name='TodoModel',
        ),
        migrations.DeleteModel(
            name='IdeasModel',
        ),
    ]
