# Generated by Django 4.0 on 2021-12-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_applicationmoduleorcomponentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationModuleOrComponentModel',
        ),
    ]
