# Generated by Django 4.0 on 2022-01-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_moduleorcomponentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleOrComponentModel',
            new_name='ModulesModel',
        ),
        migrations.AlterModelOptions(
            name='modulesmodel',
            options={'ordering': ('type_slug_field', 'current_path_slug_field', 'position_float_field', 'name_char_field'), 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelTable(
            name='modulesmodel',
            table='modules_admin_model_table',
        ),
    ]
