# Generated by Django 4.0 on 2021-12-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_ideasmodel_author_char_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdeasModel',
        ),
    ]
