# Generated by Django 3.2.9 on 2021-11-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_delete_loggingmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examplesmodel',
            table='examples_table',
        ),
    ]
