# Generated by Django 3.2.9 on 2021-11-25 15:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_examplesmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplesmodel',
            name='rational_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='описание'),
        ),
    ]
