# Generated by Django 3.2.9 on 2021-11-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_examplesmodel_rational_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplesmodel',
            old_name='rational_description',
            new_name='description',
        ),
    ]
