# Generated by Django 3.2.9 on 2021-11-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_rename_rational_description_examplesmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='название статьи')),
                ('article_text', models.TextField(blank=True, verbose_name='текст статьи')),
                ('article_pub_date', models.DateTimeField(auto_now_add=True)),
                ('article_image', models.ImageField(blank=True, upload_to='app_news/', verbose_name='картинка статьи')),
                ('article_rating_positive', models.IntegerField(default=0, verbose_name='лайки статьи')),
                ('article_rating_negative', models.IntegerField(default=0, verbose_name='дизлайки статьи')),
                ('article_rating_value', models.IntegerField(default=0, verbose_name='рейтинг статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article_table',
                'ordering': ('-id',),
            },
        ),
    ]
