# Generated by Django 3.1.6 on 2021-03-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('template_slug', models.SlugField(unique=True, verbose_name='ссылка')),
                ('template_description', models.TextField(blank=True, verbose_name='описание')),
                ('template_addition_file_1', models.FileField(blank=True, null=True, upload_to='uploads/documents/%d_%m_%Y/%H_%M_%S', verbose_name='приложение 1')),
                ('template_addition_file_2', models.FileField(blank=True, null=True, upload_to='uploads/documents/%d_%m_%Y/%H_%M_%S', verbose_name='приложение 2')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'accounttemplatetable',
                'ordering': ('-id',),
            },
        ),
    ]
