# Generated by Django 3.1.6 on 2021-03-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=50, verbose_name='название')),
                ('message_slug', models.CharField(max_length=50, verbose_name='кому')),
                ('message_description', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messagetable',
                'ordering': ('-id',),
            },
        ),
    ]
