export const USER_SALARY_LOADING_CONSTANT = "USER_SALARY_LOADING_CONSTANT";
export const USER_SALARY_DATA_CONSTANT = "USER_SALARY_DATA_CONSTANT";
export const USER_SALARY_ERROR_CONSTANT = "USER_SALARY_ERROR_CONSTANT";
export const USER_SALARY_SUCCESS_CONSTANT = "USER_SALARY_SUCCESS_CONSTANT";
export const USER_SALARY_RESET_CONSTANT = "USER_SALARY_RESET_CONSTANT";
export const USER_SALARY_DEFAULT_CONSTANT = "USER_SALARY_DEFAULT_CONSTANT";
