// export const USER_LOGIN_LOADING_CONSTANT = "USER_LOGIN_LOADING_CONSTANT";
// export const USER_LOGIN_DATA_CONSTANT = "USER_LOGIN_DATA_CONSTANT";
// export const USER_LOGIN_ERROR_CONSTANT = "USER_LOGIN_ERROR_CONSTANT";
// export const USER_LOGIN_RESET_CONSTANT = "USER_LOGIN_RESET_CONSTANT";
// export const USER_LOGIN_DEFAULT_CONSTANT = "USER_LOGIN_DEFAULT_CONSTANT";
// export const USER_LOGOUT_CONSTANT = "USER_LOGOUT_CONSTANT";

// export const USER_PROFILE_LOADING_CONSTANT = "USER_PROFILE_LOADING_CONSTANT";
// export const USER_PROFILE_DATA_CONSTANT = "USER_PROFILE_DATA_CONSTANT";
// export const USER_PROFILE_ERROR_CONSTANT = "USER_PROFILE_ERROR_CONSTANT";
// export const USER_PROFILE_RESET_CONSTANT = "USER_PROFILE_RESET_CONSTANT";
// export const USER_PROFILE_DEFAULT_CONSTANT = "USER_PROFILE_DEFAULT_CONSTANT";

// export const USER_LIST_LOADING_CONSTANT = "USER_LIST_LOADING_CONSTANT";
// export const USER_LIST_DATA_CONSTANT = "USER_LIST_DATA_CONSTANT";
// export const USER_LIST_ERROR_CONSTANT = "USER_LIST_ERROR_CONSTANT";
// export const USER_LIST_RESET_CONSTANT = "USER_LIST_RESET_CONSTANT";
// export const USER_LIST_DEFAULT_CONSTANT = "USER_LIST_DEFAULT_CONSTANT";

export const USER_LIST_LOADING_CONSTANT = "USER_LIST_LOADING_CONSTANT";
export const USER_LIST_DATA_CONSTANT = "USER_LIST_DATA_CONSTANT";
export const USER_LIST_ERROR_CONSTANT = "USER_LIST_ERROR_CONSTANT";
export const USER_LIST_RESET_CONSTANT = "USER_LIST_RESET_CONSTANT";
export const USER_LIST_DEFAULT_CONSTANT = "USER_LIST_DEFAULT_CONSTANT";

export const USER_CHANGE_LOADING_CONSTANT = "USER_CHANGE_LOADING_CONSTANT";
export const USER_CHANGE_DATA_CONSTANT = "USER_CHANGE_DATA_CONSTANT";
export const USER_CHANGE_ERROR_CONSTANT = "USER_CHANGE_ERROR_CONSTANT";
export const USER_CHANGE_RESET_CONSTANT = "USER_CHANGE_RESET_CONSTANT";
export const USER_CHANGE_DEFAULT_CONSTANT = "USER_CHANGE_DEFAULT_CONSTANT";

export const USER_RECOVER_PASSWORD_LOADING_CONSTANT =
  "USER_RECOVER_PASSWORD_LOADING_CONSTANT";
export const USER_RECOVER_PASSWORD_DATA_CONSTANT =
  "USER_RECOVER_PASSWORD_DATA_CONSTANT";
export const USER_RECOVER_PASSWORD_ERROR_CONSTANT =
  "USER_RECOVER_PASSWORD_ERROR_CONSTANT";
export const USER_RECOVER_PASSWORD_RESET_CONSTANT =
  "USER_RECOVER_PASSWORD_RESET_CONSTANT";
export const USER_RECOVER_PASSWORD_DEFAULT_CONSTANT =
  "USER_RECOVER_PASSWORD_DEFAULT_CONSTANT";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS_CONSTANT = "USER_LOGIN_SUCCESS_CONSTANT";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_CHANGE_REQUEST = "USER_CHANGE_REQUEST";
export const USER_CHANGE_SUCCESS = "USER_CHANGE_SUCCESS";
export const USER_CHANGE_FAIL = "USER_CHANGE_FAIL";
