# Generated by Django 3.1.6 on 2021-02-28 15:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/rational/category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rational_date_registrated', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('rational_structure_from', models.CharField(blank=True, max_length=50, verbose_name='имя подразделения')),
                ('rational_id_registrated', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='номер регистрации')),
                ('rational_name', models.CharField(max_length=100, verbose_name='название статьи')),
                ('rational_place_innovation', models.CharField(blank=True, max_length=200, verbose_name='место внедрения')),
                ('rational_description', ckeditor.fields.RichTextField(blank=True, verbose_name='описание')),
                ('rational_addition_file_1', models.FileField(blank=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='приложение к предложению')),
                ('rational_addition_file_2', models.FileField(blank=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='приложение 2 к предложению')),
                ('rational_addition_image', models.ImageField(blank=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='картинка к предложению')),
                ('rational_autor_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='имя автора')),
                ('rational_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rational.categoryrationalmodel')),
            ],
            options={
                'verbose_name': 'Рационализаторское предложение',
                'verbose_name_plural': 'Рационализаторские предложения',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LikeRationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('blog_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_rational.rationalmodel', verbose_name='к какому предложению')),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто поставил лайк')),
            ],
            options={
                'verbose_name': 'Лайки',
                'verbose_name_plural': 'Лайк',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CommentRationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.TextField(blank=True, verbose_name='текст комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rational.rationalmodel')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-id',),
            },
        ),
    ]
