# Generated by Django 3.1.6 on 2021-02-27 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_rational', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rationalmodel',
            options={'ordering': ('rational_date_registrated',), 'verbose_name': 'Рационализаторское предложение', 'verbose_name_plural': 'Рационализаторские предложения'},
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='rational_date_registrated',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name='дата регистрации'),
        ),
    ]
