# Generated by Django 3.1.6 on 2021-02-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationalmodel',
            name='rational_id_registrated',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='номер регистрации'),
        ),
    ]
