# Generated by Django 3.1.6 on 2021-02-27 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_rational', '0002_auto_20210227_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rationalmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Рационализаторское предложение', 'verbose_name_plural': 'Рационализаторские предложения'},
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='rational_autor_name',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='имя автора'),
        ),
        migrations.CreateModel(
            name='LikeRationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.TextField(auto_created=True, default=django.utils.timezone.now, verbose_name='дата создания')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('blog_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_rational.rationalmodel', verbose_name='к какому предложению')),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='кто поставил лайк')),
            ],
            options={
                'verbose_name': 'Лайки',
                'verbose_name_plural': 'Лайк',
                'ordering': ('-id',),
            },
        ),
    ]
