# Generated by Django 3.1.6 on 2021-02-27 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_rational', '0005_auto_20210227_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likerationalmodel',
            name='blog_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_rational.rationalmodel', verbose_name='к какому предложению'),
        ),
        migrations.AlterField(
            model_name='likerationalmodel',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто поставил лайк'),
        ),
    ]
