# Generated by Django 3.1.6 on 2021-02-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rational', '0006_auto_20210227_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationalmodel',
            name='rational_rating_negative',
        ),
        migrations.RemoveField(
            model_name='rationalmodel',
            name='rational_rating_positive',
        ),
    ]
