# Generated by Django 3.1.6 on 2021-02-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_auto_20210217_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(verbose_name='рейтинг')),
                ('rating_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.article')),
            ],
            options={
                'verbose_name': 'Рейтинги',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
    ]
