# Generated by Django 3.1.6 on 2021-02-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0004_ratingarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingarticle',
            name='rating_name',
            field=models.CharField(default=6, max_length=50, verbose_name='имя рейтинга'),
            preserve_default=False,
        ),
    ]
