# Generated by Django 3.1.6 on 2021-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0005_ratingarticle_rating_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_rating_value',
            field=models.IntegerField(default=0, verbose_name='рейтинг статьи'),
        ),
    ]
