# Generated by Django 3.1.6 on 2021-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0006_article_article_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_rating_negative',
            field=models.IntegerField(default=0, verbose_name='дизлайки статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_rating_positive',
            field=models.IntegerField(default=0, verbose_name='лайки статьи'),
        ),
    ]
