# Generated by Django 3.1.6 on 2021-02-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0008_auto_20210219_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='project_managment',
            options={'ordering': ('-id',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
