# Generated by Django 3.1.6 on 2021-02-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0009_auto_20210219_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
