# Generated by Django 3.1.6 on 2021-02-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0010_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Project_managment',
        ),
    ]
