# Generated by Django 3.1.6 on 2021-02-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
