# Generated by Django 4.0.4 on 2022-05-02 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_tokenmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenmodel',
            options={'ordering': ('-created',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Admin 7, Токены'},
        ),
        migrations.AlterField(
            model_name='tokenmodel',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_db_column', db_tablespace='user_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">ForeignKey</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_user', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
    ]
