# Generated by Django 4.0.4 on 2022-05-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tokenmodel_options_alter_tokenmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenmodel',
            options={'ordering': ('-updated',), 'verbose_name': 'Токен', 'verbose_name_plural': 'Admin 7, Токены'},
        ),
    ]
