# Generated by Django 4.0.4 on 2022-05-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_alter_tokenmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmodel',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_db_column', db_tablespace='user_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">OneToOneField</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
