# Generated by Django 3.1.6 on 2021-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('contact_slug', models.SlugField(unique=True, verbose_name='ссылка')),
                ('contact_description', models.TextField(blank=True, verbose_name='описание')),
                ('contact_image', models.ImageField(blank=True, upload_to='uploads/contact', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contacttable',
                'ordering': ('-id',),
            },
        ),
    ]
