# Generated by Django 3.2.8 on 2021-11-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_km', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankideasmodel',
            name='datetime_register',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Дата регистрации'),
        ),
    ]
