# Generated by Django 3.2.8 on 2021-11-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_km', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatamodel',
            name='category',
            field=models.TextField(blank=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='accountdatamodel',
            name='department_site',
            field=models.TextField(blank=True, verbose_name='Отдел/Участок'),
        ),
        migrations.AddField(
            model_name='accountdatamodel',
            name='personnel_number',
            field=models.TextField(blank=True, verbose_name='Табельный номер'),
        ),
        migrations.AddField(
            model_name='accountdatamodel',
            name='subdivision',
            field=models.TextField(blank=True, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='accountdatamodel',
            name='workshop_service',
            field=models.TextField(blank=True, verbose_name='Цех/Служба'),
        ),
    ]
