# Generated by Django 3.2.8 on 2021-11-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_km', '0002_groupsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupsModel',
        ),
    ]
