# Generated by Django 4.0 on 2022-01-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_admin', '0003_chatmodel_computervisionmodulemodel_ideamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
