# Generated by Django 3.1.6 on 2021-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('application_slug', models.SlugField(unique=True, verbose_name='ссылка')),
                ('application_description', models.TextField(blank=True, verbose_name='описание')),
                ('application_image', models.ImageField(blank=True, upload_to='uploads/contact', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'db_table': 'applicationtable',
                'ordering': ('-id',),
            },
        ),
    ]
