# Generated by Django 3.1.6 on 2021-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomponentmodel',
            name='component_image',
            field=models.ImageField(blank=True, upload_to='uploads/application/component', verbose_name='картинка закладки'),
        ),
        migrations.AlterField(
            model_name='applicationmodulemodel',
            name='module_image',
            field=models.ImageField(blank=True, upload_to='uploads/application/module', verbose_name='картинка'),
        ),
    ]
