# Generated by Django 3.1.6 on 2021-03-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='application_description',
            field=models.TextField(blank=True, verbose_name='описание в заголовке меню'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='application_image',
            field=models.ImageField(blank=True, upload_to='uploads/application/icons', verbose_name='картинка в заголовке меню'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='application_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='название приложения'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='application_slug',
            field=models.SlugField(unique=True, verbose_name='ссылка на приложение'),
        ),
    ]
