# Generated by Django 3.1.6 on 2021-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0002_auto_20210309_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='application_position',
            field=models.IntegerField(blank=True, default=0, verbose_name='позиция в списке приложений'),
            preserve_default=False,
        ),
    ]
