# Generated by Django 3.1.6 on 2021-03-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0002_auto_20210314_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomponentmodel',
            name='component_position',
            field=models.IntegerField(verbose_name='позиция в списке закладок'),
        ),
    ]
