# Generated by Django 3.1.6 on 2021-03-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0003_auto_20210314_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcomponentmodel',
            options={'ordering': ('component_Foreign', 'component_position'), 'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterField(
            model_name='applicationmodulemodel',
            name='module_position',
            field=models.IntegerField(verbose_name='позиция'),
        ),
    ]
