# Generated by Django 3.1.6 on 2021-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0003_applicationmodel_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='application_position',
            field=models.IntegerField(unique=True, verbose_name='позиция в списке приложений'),
        ),
    ]
