# Generated by Django 3.1.6 on 2021-03-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0004_auto_20210310_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortcutApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut_application_name', models.TextField(verbose_name='название закладки')),
                ('shortcut_application_description', models.TextField(verbose_name='описание закладки')),
                ('shortcut_application_slug', models.SlugField(unique=True, verbose_name='ссылка закладки')),
                ('shortcut_application_image', models.ImageField(blank=True, upload_to='uploads/application/icons/shortcut', verbose_name='картинка закладки')),
                ('shortcut_application_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_application.applicationmodel', verbose_name='приложение')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'db_table': 'shortcutapplicationtable',
                'ordering': ('-id',),
            },
        ),
    ]
