# Generated by Django 3.1.6 on 2021-03-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0006_shortcutapplicationmodel_shortcut_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='application_slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='ссылка на приложение'),
        ),
        migrations.AlterField(
            model_name='shortcutapplicationmodel',
            name='shortcut_application_slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='ссылка закладки'),
        ),
    ]
