version: '2'
services:
 db:
   image: "postgres:9.6-alpine"
   environment:
     POSTGRES_PASSWORD: admin
     POSTGRES_USER: admin
   ports:
     - "15432:5432"
 redis:
   image: "redis:3.0-alpine"
   ports:
     - "16379:6379"