# Generated by Django 4.0 on 2021-12-21 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_actionmodel_loggingmodel_moduleorcomponentmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(max_length=150)),
                ('data_description', models.CharField(blank=True, max_length=300)),
                ('data_date', models.DateTimeField(auto_now_add=True)),
                ('data_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IdeasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_char_field', models.CharField(blank=True, db_column='author_char_field_db_column', db_index=True, db_tablespace='author_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">author_char_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Автор')),
                ('name_char_field', models.CharField(blank=True, db_column='name_char_field_db_column', db_index=True, db_tablespace='name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">name_char_field</small><hr><br>', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(32)], verbose_name='Название')),
                ('category_slug_field', models.SlugField(blank=True, choices=[('innovation', 'Инновации'), ('optimization', 'Оптимизации'), ('industry', 'Индустрия 4.0'), ('other', 'Другое')], db_column='category_slug_field_db_column', db_tablespace='category_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">category_slug_field</small><hr><br>', max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(16)], verbose_name='Категория')),
                ('short_description_char_field', models.CharField(blank=True, db_column='short_description_char_field_db_column', db_index=True, db_tablespace='short_description_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">short_description_char_field</small><hr><br>', max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(64)], verbose_name='Краткое описание')),
                ('full_description_text_field', models.TextField(blank=True, db_column='full_description_text_field_db_column', db_index=True, db_tablespace='full_description_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">full_description_text_field</small><hr><br>', max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1024)], verbose_name='Полное описание')),
                ('avatar_image_field', models.ImageField(blank=True, db_column='avatar_image_field_db_column', db_index=True, db_tablespace='avatar_image_field_db_tablespace', default='uploads/idea/default_avatar.jpg', error_messages=False, help_text='<small class="text-muted">>avatar_image_field</small><hr><br>', null=True, upload_to='uploads/idea/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Аватарка-заставка для идеи')),
                ('addiction_file_field', models.FileField(blank=True, db_column='addiction_file_field_db_column', db_index=True, db_tablespace='addiction_file_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">addiction_file_field</small><hr><br>', null=True, upload_to='uploads/idea/files/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'docx', 'doc', 'pdf'])], verbose_name='Файл-приложение')),
                ('visibility_boolean_field', models.BooleanField(blank=True, db_column='visibility_boolean_field_db_column', db_index=True, db_tablespace='visibility_boolean_field_db_tablespace', default=False, error_messages=False, help_text='<small class="text-muted">visibility_boolean_field</small><hr><br>', verbose_name='Видимость идеи в общем списке')),
                ('created_datetime_field', models.DateTimeField(blank=True, db_column='created_datetime_field_db_column', db_index=True, db_tablespace='created_datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">created_datetime_field</small><hr><br>', null=True, verbose_name='Дата создания')),
                ('register_datetime_field', models.DateTimeField(blank=True, db_column='register_datetime_field_db_column', db_index=True, db_tablespace='register_datetime_field_db_tablespace', default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">register_datetime_field</small><hr><br>', null=True, verbose_name='Дата регистрации')),
                ('author_foreign_key_field', models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.usermodel', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': '0_Идеи',
                'db_table': 'ideas_model_table',
                'ordering': ('-id',),
            },
        ),
    ]
