# Generated by Django 4.0 on 2021-12-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_djangorestframework', '0003_ideasmodel_rename_data_datamodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasmodel',
            name='addiction_file_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='avatar_image_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='category_slug_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='created_datetime_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='full_description_text_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='name_char_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='register_datetime_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='short_description_char_field',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='visibility_boolean_field',
        ),
    ]
