# Generated by Django 4.0 on 2021-12-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_alter_actionmodel_type_slug_field'),
        ('app_djangorestframework', '0006_ideasmodel_addiction_file_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasmodel',
            name='author_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.usermodel', verbose_name='Автор'),
        ),
    ]
