export const NOTES_LIST_REQUEST = "NOTES_LIST_REQUEST";
export const NOTES_LIST_SUCCESS = "NOTES_LIST_SUCCESS";
export const NOTES_LIST_FAIL = "NOTES_LIST_FAIL";

export const NOTES_DETAIL_REQUEST = "NOTES_DETAIL_REQUEST";
export const NOTES_DETAIL_SUCCESS = "NOTES_DETAIL_SUCCESS";
export const NOTES_DETAIL_FAIL = "NOTES_DETAIL_FAIL";