# Generated by Django 3.1.4 on 2020-12-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
