# Generated by Django 3.1.4 on 2020-12-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20201223_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(default='Title', max_length=300),
        ),
    ]
