# Generated by Django 3.1.4 on 2020-12-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='project_managment',
            options={'ordering': ('name',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
