# Generated by Django 3.1.4 on 2020-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_managment',
            name='button_text',
            field=models.CharField(max_length=15),
        ),
    ]
