# Generated by Django 4.0 on 2022-01-06 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_ideasmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasmodel',
            name='author_foreign_key_field',
        ),
        migrations.AddField(
            model_name='ideasmodel',
            name='author_char_field',
            field=models.CharField(blank=True, db_column='author_char_field_db_column', db_index=True, db_tablespace='author_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted underline">кириллица, любой регистр, можно с пробелами, например: "Модератор отдела ОУПиБП"</small><hr><br>', max_length=128, null=True, unique_for_date=False, unique_for_month=False, unique_for_year=False, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Автор'),
        ),
    ]
