# Generated by Django 3.1.6 on 2021-02-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wheather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-id',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
