# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wheather', '0002_auto_20210219_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, verbose_name='город'),
        ),
    ]
