# Generated by Django 4.0 on 2022-02-18 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email_field',
            field=models.EmailField(blank=True, db_column='email_field_db_column', db_index=True, db_tablespace='email_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Строка содержащая почту, example: "bogdandrienko@gmail.com"</small><hr><br>', max_length=254, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(254)], verbose_name='email_field'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name_char_field',
            field=models.CharField(blank=True, db_column='first_char_field_db_column', db_index=True, db_tablespace='first_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">first_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name_char_field',
            field=models.CharField(blank=True, db_column='last_name_char_field_db_column', db_index=True, db_tablespace='last_name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">last_name_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password_slug_field',
            field=models.SlugField(blank=True, db_column='password_slug_field_db_column', db_tablespace='password_slug_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">password_slug_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(128)], verbose_name='Пароль от аккаунта пользователя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='patronymic_char_field',
            field=models.CharField(blank=True, db_column='patronymic_char_field_db_column', db_index=True, db_tablespace='patronymic_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">patronymic_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='secret_answer_char_field',
            field=models.CharField(blank=True, db_column='secret_answer_char_field_db_column', db_index=True, db_tablespace='secret_answer_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">secret_answer_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Секретный ответ'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='secret_question_char_field',
            field=models.CharField(blank=True, db_column='secret_question_char_field_db_column', db_index=True, db_tablespace='secret_question_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">secret_question_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Секретный вопрос'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='subdivision_char_field',
            field=models.CharField(blank=True, db_column='subdivision_char_field_db_column', db_index=True, db_tablespace='subdivision_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">subdivision_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Подразделение'),
        ),
    ]
