# Generated by Django 4.0 on 2022-02-21 09:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationalmodel',
            name='addiction_file_field',
        ),
        migrations.RemoveField(
            model_name='rationalmodel',
            name='full_description_text_field',
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='additional_excel_file_field',
            field=models.FileField(blank=True, db_column='additional_excel_file_field_db_column', db_index=True, db_tablespace='additional_excel_file_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">additional_excel_file_field</small><hr><br>', max_length=200, null=True, upload_to='uploads/idea/files/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls'])], verbose_name='Excel файл-приложение'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='additional_pdf_file_field',
            field=models.FileField(blank=True, db_column='additional_pdf_file_field_db_column', db_index=True, db_tablespace='additional_pdf_file_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">additional_pdf_file_field</small><hr><br>', max_length=200, null=True, upload_to='uploads/idea/files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Pdf файл-приложение'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='additional_word_file_field',
            field=models.FileField(blank=True, db_column='additional_word_file_field_db_column', db_index=True, db_tablespace='additional_word_file_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">additional_word_file_field</small><hr><br>', max_length=200, null=True, upload_to='uploads/idea/files/', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])], verbose_name='Word файл-приложение'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='description_text_field',
            field=models.TextField(blank=True, db_column='description_text_field_db_column', db_index=True, db_tablespace='description_text_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">description_text_field</small><hr><br>', max_length=2048, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(2048)], verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='place_char_field',
            field=models.CharField(blank=True, db_column='place_char_field_db_column', db_index=True, db_tablespace='place_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">place_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Предполагаемое место внедрения'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='sphere_char_field',
            field=models.CharField(blank=True, db_column='sphere_char_field_db_column', db_index=True, db_tablespace='sphere_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">sphere_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Сфера рац. предложения'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='subdivision_char_field',
            field=models.CharField(blank=True, db_column='subdivision_char_field_db_column', db_index=True, db_tablespace='subdivision_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">subdivision_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Наименование структурного подразделения'),
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='author_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.usermodel', verbose_name='Автор рац. предложения'),
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='avatar_image_field',
            field=models.ImageField(blank=True, db_column='avatar_image_field_db_column', db_index=True, db_tablespace='avatar_image_field_db_tablespace', default='uploads/rational/default_rational.jpg', error_messages=False, help_text='<small class="text-muted">>avatar_image_field</small><hr><br>', max_length=200, null=True, upload_to='uploads/rational/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Аватарка-заставка для идеи'),
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='category_char_field',
            field=models.CharField(blank=True, db_column='category_char_field_db_column', db_index=True, db_tablespace='category_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">category_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='name_char_field',
            field=models.CharField(blank=True, db_column='name_char_field_db_column', db_index=True, db_tablespace='name_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">name_char_field</small><hr><br>', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(128)], verbose_name='Название рац. предложения'),
        ),
        migrations.AlterField(
            model_name='rationalmodel',
            name='short_description_char_field',
            field=models.CharField(blank=True, db_column='short_description_char_field_db_column', db_index=True, db_tablespace='short_description_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">short_description_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='Краткое описание'),
        ),
    ]
