# Generated by Django 4.0 on 2022-02-22 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_rationalmodel_addiction_file_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationalmodel',
            name='number_char_field',
            field=models.CharField(blank=True, db_column='number_char_field_db_column', db_index=True, db_tablespace='number_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">number_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='number'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='user1_char_field',
            field=models.CharField(blank=True, db_column='user1_char_field_db_column', db_index=True, db_tablespace='user1_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">user1_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='user1'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='user2_char_field',
            field=models.CharField(blank=True, db_column='user2_char_field_db_column', db_index=True, db_tablespace='user2_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">user2_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='user2'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='user3_char_field',
            field=models.CharField(blank=True, db_column='user3_char_field_db_column', db_index=True, db_tablespace='user3_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">user3_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='user3'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='user4_char_field',
            field=models.CharField(blank=True, db_column='user4_char_field_db_column', db_index=True, db_tablespace='user4_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">user4_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='user4'),
        ),
        migrations.AddField(
            model_name='rationalmodel',
            name='user5_char_field',
            field=models.CharField(blank=True, db_column='user5_char_field_db_column', db_index=True, db_tablespace='user5_char_field_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">user5_char_field</small><hr><br>', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(256)], verbose_name='user5'),
        ),
    ]
