# Generated by Django 3.2.4 on 2021-07-26 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_account', '0003_accountdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatamodel',
            name='user_iin',
            field=models.IntegerField(blank=True, default=0, verbose_name='ИИН пользователя'),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='username',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
    ]
