# Generated by Django 3.2.4 on 2021-07-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_alter_accountdatamodel_image_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatamodel',
            name='group',
            field=models.SlugField(blank=True, max_length=64, verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='password',
            field=models.SlugField(blank=True, max_length=64, verbose_name='пароль'),
        ),
    ]
