# Generated by Django 3.2.4 on 2021-07-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0006_auto_20210726_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatamodel',
            name='user_iin',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='ИИН пользователя'),
        ),
    ]
