# Generated by Django 3.2.4 on 2021-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0007_alter_accountdatamodel_user_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatamodel',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='user_iin',
            field=models.IntegerField(blank=True, unique=True, verbose_name='ИИН пользователя'),
        ),
    ]
