# Generated by Django 3.1.6 on 2021-02-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingArticle',
        ),
    ]
