# Generated by Django 3.1.6 on 2021-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_delete_ratingarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
