# Generated by Django 4.0 on 2022-01-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamplesModel',
        ),
    ]
