# Generated by Django 4.0 on 2022-01-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0003_delete_loggingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleOrComponentModel',
        ),
    ]
