# Generated by Django 4.0 on 2022-01-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_actionmodel_usermodel_notificationmodel_groupmodel'),
        ('app_django', '0004_delete_moduleorcomponentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='action_many_to_many_field',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='group_foreign_key_field',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='user_many_to_many_field',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='user_foreign_key_field',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_foreign_key_field',
        ),
        migrations.AlterField(
            model_name='ideacommentmodel',
            name='author_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.usermodel', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='author_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.usermodel', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='idearatingmodel',
            name='author_foreign_key_field',
            field=models.ForeignKey(blank=True, db_column='author_foreign_key_field_db_column', db_tablespace='author_foreign_key_field_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">author_foreign_key_field</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.usermodel', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='ActionModel',
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
        migrations.DeleteModel(
            name='NotificationModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
