# Generated by Django 4.0 on 2022-01-11 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0016_delete_ideasmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRationalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('category_slug', models.SlugField(unique=True, verbose_name='ссылка')),
                ('category_description', models.TextField(blank=True, verbose_name='описание')),
                ('category_image', models.ImageField(blank=True, upload_to='uploads/rational/category', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categoryrationaltable',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RationalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rational_date_certification', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name='дата получения удостоверения на предложение')),
                ('rational_date_registrated', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('rational_structure_from', models.CharField(blank=True, max_length=50, verbose_name='имя подразделения')),
                ('rational_uid_registrated', models.IntegerField(blank=True, default=0, verbose_name='номер регистрации')),
                ('rational_name', models.CharField(max_length=50, verbose_name='название статьи')),
                ('rational_place_innovation', models.CharField(blank=True, max_length=100, verbose_name='место внедрения')),
                ('rational_addition_file_1', models.FileField(blank=True, null=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='приложение 1')),
                ('rational_addition_file_2', models.FileField(blank=True, null=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='приложение 2')),
                ('rational_addition_file_3', models.FileField(blank=True, null=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='приложение 3')),
                ('rational_resolution', models.CharField(blank=True, max_length=200, verbose_name='принятое решение')),
                ('rational_date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('rational_addition_image', models.ImageField(blank=True, upload_to='uploads/rational/%d_%m_%Y/%H_%M_%S', verbose_name='картинка к предложению')),
                ('rational_status', models.BooleanField(blank=True, default=False, verbose_name='статус')),
                ('rational_autor_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='имя автора')),
                ('rational_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_rational.categoryrationalmodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рационализаторское предложение',
                'verbose_name_plural': 'Рационализаторские предложения',
                'db_table': 'rationaltable',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LikeRationalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.BooleanField(default=False, verbose_name='лайк/дизлайк')),
                ('like_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('like_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rational.rationalmodel', verbose_name='предложение')),
                ('like_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'db_table': 'likerationaltable',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CommentRationalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='текст')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rational.rationalmodel', verbose_name='предложение')),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'commentrationaltable',
                'ordering': ('-id',),
            },
        ),
    ]
