# Generated by Django 3.1.6 on 2021-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_name', models.CharField(max_length=50, verbose_name='название')),
                ('notification_slug', models.CharField(max_length=50, verbose_name='ссылка')),
                ('notification_description', models.TextField(verbose_name='описание')),
                ('notification_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('notification_status', models.BooleanField(default=False, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notificationtable',
                'ordering': ('-id',),
            },
        ),
    ]
