# Generated by Django 3.1.6 on 2021-03-22 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'ordering': ('-notification_status', '-notification_date'), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_status',
            field=models.BooleanField(default=True, verbose_name='статус'),
        ),
    ]
