# Generated by Django 3.2.4 on 2021-07-26 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_account', '0002_alter_accounttemplatemodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.SlugField(max_length=64, verbose_name='пароль')),
                ('firstname', models.TextField(blank=True, verbose_name='Имя')),
                ('lastname', models.TextField(blank=True, verbose_name='Фамилия')),
                ('patronymic', models.TextField(blank=True, verbose_name='Отчество')),
                ('position', models.TextField(blank=True, verbose_name='Должность')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('hobbies', models.TextField(blank=True, verbose_name='Увлечения')),
                ('mail', models.TextField(blank=True, verbose_name='Электронная почта')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('secret_question', models.TextField(blank=True, verbose_name='Секретный вопрос')),
                ('image_avatar', models.ImageField(blank=True, upload_to='uploads/account/avatar', verbose_name='Аватарка')),
                ('group', models.SlugField(max_length=64, verbose_name='группы')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='статус')),
                ('username', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ИИН пользователя')),
            ],
            options={
                'verbose_name': 'Данные аккаунта',
                'verbose_name_plural': 'Данные аккаунтов',
                'db_table': 'accountdatatable',
                'ordering': ('-id',),
            },
        ),
    ]
