# Generated by Django 3.2.4 on 2021-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_auto_20210726_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatamodel',
            name='image_avatar',
            field=models.ImageField(blank=True, default='uploads/account/avatar/default.jpg', upload_to='uploads/account/avatar', verbose_name='Аватарка'),
        ),
    ]
